[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = [
    "-h",
] }

[tasks.objcopy-central]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "central",
    "--",
    "-O",
    "ihex",
    "ehrbl-central.hex",
]
dependencies = ["install-llvm-tools", "flip-link"]

[tasks.objcopy-peripheral]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
args = [
    "objcopy",
    "--release",
    "--bin",
    "peripheral",
    "--",
    "-O",
    "ihex",
    "ehrbl-peripheral.hex",
]
dependencies = ["install-llvm-tools"]

[tasks.uf2-central]
command = "python"
args = [
    "scripts/uf2conv.py",
    "ehrbl-central.hex",
    "-c",
    "-f",
    "NRF52840",      
    "-o",
    "ehrbl-central.uf2",
]
dependencies = ["objcopy-central"]

[tasks.uf2-peripheral]
command = "python"
args = [
    "scripts/uf2conv.py",
    "ehrbl-peripheral.hex",
    "-c",
    "-f",
    "NRF52840",
    "-o",
    "ehrbl-peripheral.uf2",
]
dependencies = ["objcopy-peripheral"]

[tasks.uf2]
dependencies = ["uf2-central", "uf2-peripheral"]
