name: Build123d

on:
  push:
    paths:
      - ".github/workflows/case.yml"
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/case.yml"
  workflow_dispatch:

jobs:
  Case:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          variant: case
          skip: erc,drc
          targets: EDGES CASE_DRILL
      # Then run again to get power switch locations for edge cuts
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          skip: erc,drc
          targets: JLCPCB_POSITION
      - run: |
          echo "Installing dependencies..."
          python3 -m pip install build123d
          echo "Generating case..."
          python .github/workflows/case.py
          echo "Done."
      - uses: actions/upload-artifact@v4
        with:
          name: case
          path: case.*

  Release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: Case
    permissions:
      contents: write # allow workflow to commit to the rep
    steps:
      - uses: actions/download-artifact@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: case/*
