name: KiBot

# Controls when the action will run.
on:
  push:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  pull_request:
    paths:
      - "*.kicad_sch"
      - "*.kicad_pcb"
      - "*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ERC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          skip: drc
          targets: __NONE__

  DRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          skip: erc
          targets: __NONE__

  BOARD:
    runs-on: ubuntu-latest
    needs: [ERC, DRC]
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk8
        with:
          variant: board
          skip: erc,drc
          targets: SCHEMATIC ZIP_ASSEMBLY
      - uses: actions/upload-artifact@v4
        with:
          name: schematic
          path: schematic.svg
      - uses: actions/upload-artifact@v4
        with:
          name: pcb
          path: jlcpcb.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: BOARD
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pcb
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "jlcpcb.zip"
